// src/components/layout/Navbar.tsx
'use client';

import { config } from '@/data/portfolio.config';

const navLinks = [
  { label: 'Work', href: '#work' },
  { label: 'Experience', href: '#experience' },
  { label: 'AI DNA', href: '#ai-dna' },
  { label: 'Contact', href: '#contact' },
];

export default function Navbar() {
  return (
    <nav className="sticky top-0 z-50 bg-bg-base/80 backdrop-blur-sm border-b border-bg-border">
      <div className="max-w-content mx-auto px-6 py-4 flex items-center justify-between">
        {/* Left: DM Monogram */}
        <a href="/" className="shrink-0">
          <span className="font-mono text-accent font-bold text-lg border border-accent/30 px-2 py-1 rounded">
            DM
          </span>
        </a>

        {/* Center: Nav links (hidden on mobile) */}
        <div className="hidden md:flex items-center gap-8">
          {navLinks.map((link) => (
            <a
              key={link.href}
              href={link.href}
              className="text-text-secondary hover:text-text-primary text-sm transition-colors"
            >
              {link.label}
            </a>
          ))}
        </div>

        {/* Right: 3D mode + Resume download */}
        <div className="flex items-center gap-3">
          <a
            href="/3d"
            className="text-xs font-mono tracking-widest uppercase border border-white/20 text-text-secondary px-4 py-2 hover:border-accent hover:text-accent transition-all"
          >
            3D
          </a>
          <a
            href="/assets/data/resume.pdf"
            download
            className="text-xs font-mono tracking-widest uppercase border border-accent text-accent px-4 py-2 hover:bg-accent hover:text-bg-base transition-all"
          >
            Resume
          </a>
        </div>
      </div>
    </nav>
  );
}

// src/app/components/navbar/navbar.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DarkModeToggle } from '../dark-mode-toggle/dark-mode-toggle.component';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, DarkModeToggle],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class Navbar {
  isMobileMenuOpen = signal(false);
  
  navItems = [
    { label: 'Home', href: '#home' },
    { label: 'About', href: '#about' },
    { label: 'Skills', href: '#skills' },
    { label: 'Projects', href: '#projects' },
    { label: 'Experience', href: '#experience' },
    { label: 'Contact', href: '#contact' }
  ];

  scrollToSection(href: string): void {
    const element = document.querySelector(href);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
    // Close mobile menu after navigation
    this.isMobileMenuOpen.set(false);
  }

  toggleMobileMenu(): void {
    this.isMobileMenuOpen.set(!this.isMobileMenuOpen());
  }
}

<nav class="fixed top-0 left-0 right-0 z-50 bg-white/80 dark:bg-gray-900/80 backdrop-blur-md border-b border-gray-200 dark:border-gray-700">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between items-center h-16">
      <!-- Logo/Brand -->
      <div class="flex-shrink-0">
        <a href="#home" class="text-xl font-bold text-gray-900 dark:text-white hover:text-blue-600 dark:hover:text-blue-400 transition-colors">
          Dhanish Mehta
        </a>
      </div>

      <!-- Desktop Navigation -->
      <div class="hidden md:block">
        <div class="ml-10 flex items-baseline space-x-4">
          <a 
            *ngFor="let item of navItems" 
            (click)="scrollToSection(item.href)"
            class="text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 px-3 py-2 rounded-md text-sm font-medium cursor-pointer transition-colors"
          >
            {{ item.label }}
          </a>
        </div>
      </div>

      <!-- Dark Mode Toggle -->
      <div class="flex items-center space-x-4">
        <app-dark-mode-toggle></app-dark-mode-toggle>
        
        <!-- Mobile menu button -->
        <button 
          class="md:hidden p-2 rounded-md text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 focus:outline-none"
          (click)="toggleMobileMenu()"
        >
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
        </button>
      </div>
    </div>

    <!-- Mobile Navigation -->
    <div class="md:hidden" [class.hidden]="!isMobileMenuOpen()">
      <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
        <a 
          *ngFor="let item of navItems" 
          (click)="scrollToSection(item.href)"
          class="text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 block px-3 py-2 rounded-md text-base font-medium cursor-pointer transition-colors"
        >
          {{ item.label }}
        </a>
      </div>
    </div>
  </div>
</nav>
